# **DATA MANIPULATION WITH PANDAS**

# 2. Data frame

In [ ]:
import pandas as pd
students = {
    "name": ["harsh", "ankit", "kanishka"],
    "roll_no": [100,101,102],
    "marks": [80,86,68],
}
DF = pd.DataFrame(students)
print(DF)

       name  roll_no  marks
0     harsh      100     80
1     ankit      101     86
2  kanishka      102     68

In [ ]:
import pandas as pd
students = {
    "name": ["ankit", "kanishka"],
    "roll_no": [100,101,102],
    "marks": [80,88,86],
}
DF = pd.DataFrame(students)
print(DF)

ValueError: All arrays must be of the same length

### *Creating a data frame with list*

In [ ]:
import pandas as pd
Studentsinfo = [['A','B','C'], [20,40,60]]
DF = pd.DataFrame(Studentsinfo)
print(DF)

    0   1   2
0   A   B   C
1  20  40  60

In [ ]:
import pandas as pd
Studentsinfo = [['A','B','C'], [20,40,60]]
DF = pd.DataFrame(Studentsinfo, index = ['name','marks'])
DF

        0   1   2
name    A   B   C
marks  20  40  60

In [ ]:
import pandas as pd
Sr = {
    "name": pd.Series(['A','B','C','D', 'E']),
    "roll_no": pd.Series([10,11,12,13,14,15]),
}
DF = pd.DataFrame(Sr)
print(DF)

  name  roll_no
0    A       10
1    B       11
2    C       12
3    D       13
4    E       14
5  NaN       15

 Arithmetic operations in data frame

In [ ]:
import pandas as pd
var = pd.DataFrame({'A': [1,2,3,4], 'B': [5,6,7,8]})
print(var)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [ ]:
import pandas as pd
var = pd.DataFrame({'A': [1,2,3,4], 'B': [5,6,7,8]})
var = var["A"] + var["B"]
var

0     6
1     8
2    10
3    12
dtype: int64

 Filtering in data frame

In [ ]:
import pandas as pd
var = pd.DataFrame({'A': [1,2,3,4], 'B': [5,6,7,8]})
var = var["A"] + var["B"]
var["python"] = var > 10
var

0                                                         6
1                                                         8
2                                                        10
3                                                        12
python    0    False
1    False
2    False
3     True
dt...
dtype: object

Handling missing values*

In [ ]:
import numpy as np
info = {
    "name": ['A','B','C','D','np.nan'],
    "roll_no": [10,20,30,40,np.nan],
    "marks": [20,30,40,np.nan,50],
     "city": ['a','b','c','d','e'],
}
DF = pd.DataFrame(info)
DF

     name  roll_no  marks city
0       A     10.0   20.0    a
1       B     20.0   30.0    b
2       C     30.0   40.0    c
3       D     40.0    NaN    d
4  np.nan      NaN   50.0    e

In [ ]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll_no  4 non-null      float64
 2   marks    4 non-null      float64
 3   city     5 non-null      object
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
DF.isnull()

    name  roll_no  marks   city
0  False    False  False  False
1  False    False  False  False
2  False    False  False  False
3  False    False   True  False
4  False     True  False  False

In [ ]:
DF.isnull().sum()

name       0
roll_no    1
marks      1
city       0
dtype: int64

In [ ]:
print(DF.isnull().sum().sum())

2

In [ ]:
#Remove null values
DF.dropna()

  name  roll_no  marks city
0    A     10.0   20.0    a
1    B     20.0   30.0    b
2    C     30.0   40.0    c

In [ ]:
DF.dropna(subset= ["marks"])

     name  roll_no  marks city
0       A     10.0   20.0    a
1       B     20.0   30.0    b
2       C     30.0   40.0    c
4  np.nan      NaN   50.0    e

In [ ]:
DF["marks"]= DF["marks"].fillna(0)
DF

     name  roll_no  marks city
0       A     10.0   20.0    a
1       B     20.0   30.0    b
2       C     30.0   40.0    c
3       D     40.0    0.0    d
4  np.nan      NaN   50.0    e

In [ ]:
DF["marks"]= DF["marks"].fillna(DF["marks"].mean())
DF

     name  roll_no  marks city
0       A     10.0   20.0    a
1       B     20.0   30.0    b
2       C     30.0   40.0    c
3       D     40.0    0.0    d
4  np.nan      NaN   50.0    e

In [ ]:
DF["marks"] = DF["marks"].fillna(DF["marks"].median())
DF

     name  roll_no  marks city
0       A     10.0   20.0    a
1       B     20.0   30.0    b
2       C     30.0   40.0    c
3       D     40.0    0.0    d
4  np.nan      NaN   50.0    e

In [ ]:
DF["name"].fillna("ankit")

0         A
1         B
2         C
3         D
4    np.nan
Name: name, dtype: object