# **MERGING AND JOINING**

## 1. MERGE(): Column based

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A':[2,3,4,5], 'B': ['A', 'B', 'C', 'D']})
df2 = pd.DataFrame({'A':[1,2,3,4], 'C': ['A1', 'B1', 'C1', 'D1']})
pd.merge(df1, df2)

   A  B   C
0  2  A  B1
1  3  B  C1
2  4  C  D1

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A':[2,3,4,5], 'B': ['A', 'B', 'C', 'D']})
df2 = pd.DataFrame({'A':[1,2,3,4], 'C': ['A1', 'B1', 'C1', 'D1']})
pd.merge(df1, df2, on = 'A', how='inner')

   A  B   C
0  2  A  B1
1  3  B  C1
2  4  C  D1

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A':[2,3,4,5], 'B': ['A', 'B', 'C', 'D']})
df2 = pd.DataFrame({'A':[1,2,3,4], 'C': ['A1', 'B1', 'C1', 'D1']})
pd.merge(df1, df2, on = 'A', how='outer')

   A    B    C
0  1  NaN   A1
1  2    A   B1
2  3    B   C1
3  4    C   D1
4  5    D  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A':[2,3,4,5], 'B': ['A', 'B', 'C', 'D']})
df2 = pd.DataFrame({'A':[1,2,3,4], 'C': ['A1', 'B1', 'C1', 'D1']})
pd.merge(df1, df2, on = 'A', how='left')

   A  B    C
0  2  A   B1
1  3  B   C1
2  4  C   D1
3  5  D  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A':[2,3,4,5], 'B': ['A', 'B', 'C', 'D']})
df2 = pd.DataFrame({'A':[1,2,3,4], 'C': ['A1', 'B1', 'C1', 'D1']})
pd.merge(df1, df2, on = 'A', how='right')

   A    B   C
0  1  NaN  A1
1  2    A  B1
2  3    B  C1
3  4    C  D1

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A':[2,3,4,5], 'B': ['A', 'B', 'C', 'D']})
df2 = pd.DataFrame({'A':[1,2,3,4], 'B': ['A1', 'B1', 'C1', 'D1']})
pd.merge(df1, df2)

Empty DataFrame
Columns: [A, B]
Index: []

In [ ]:
import pandas as pd
v1 = pd.DataFrame({'A':[2,3,4,5], 'B': ['A', 'B', 'C', 'D']})
v2 = pd.DataFrame({'A':[1,2,3,4], 'B': ['A1', 'B1', 'C1', 'D1']})
pd.merge(v1, v2)

Empty DataFrame
Columns: [A, B]
Index: []

In [ ]:
import pandas as pd
v1 = pd.DataFrame({'A':[2,3,4,5], 'A': ['A', 'B', 'C', 'D']})
v2 = pd.DataFrame({'B':[1,2,3,4], 'B': ['A1', 'B1', 'C1', 'D1']})                    #it will give error as column names are same
pd.merge(v1, v2)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [ ]:
import pandas as pd
v1 = pd.DataFrame({'A':[2,3,4,5], 'A': ['A', 'B', 'C', 'D']})
v2 = pd.DataFrame({'A':[1,2,3,4], 'A': ['A1', 'B1', 'C1', 'D1']})
pd.merge(v1,v2)

Empty DataFrame
Columns: [A]
Index: []

In [ ]:
import pandas as pd
v1 = pd.DataFrame({'A':[2,3,4,5], 'B': ['A', 'B', 'C', 'D']})
v2 = pd.DataFrame({'A':[2,3,4,5], 'C': ['A1', 'B1', 'C1', 'D1']})
pd.merge(v1,v2)

   A  B   C
0  2  A  A1
1  3  B  B1
2  4  C  C1
3  5  D  D1

In [ ]:
v1 = pd.DataFrame({"roll_no": [20,30,40], "name":['A','B','C']})
v2 = pd.DataFrame({"roll_no": [20,30,40], "marks":['60','70','80']})
SI = pd.merge(v1,v2)
print(SI)

   roll_no name marks
0       20    A    60
1       30    B    70
2       40    C    80

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"roll_no": [20,30,40], "name":['sonali','kanishka','sadaf']})
v2 = pd.DataFrame({"roll_no": [20,30,40], "marks":['60','70','80']})
SI = pd.merge(v1,v2)
print(SI)

   roll_no      name marks
0       20    sonali    60
1       30  kanishka    70
2       40     sadaf    80

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"roll_no": [1,2,3,4,5], "name":['sonali','kanishka','sadaf', 'pragya', 'umang']})
v2 = pd.DataFrame({"roll_no": [1,2,3,4,5], "marks":['60','70','80','90','100']})
Student_info = pd.merge(v1,v2, how = "inner")
print(Student_info)

   roll_no      name marks
0        1    sonali    60
1        2  kanishka    70
2        3     sadaf    80
3        4    pragya    90
4        5     umang   100

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"roll_no": [1,2,3,4,5], "name":['sonali','kanishka','sadaf', 'pragya', 'umang']})
v2 = pd.DataFrame({"roll_no": [1,2,3,4,6], "marks":['60','70','80','90','100']})
pd.merge(v1,v2,how = 'outer')

   roll_no      name marks
0        1    sonali    60
1        2  kanishka    70
2        3     sadaf    80
3        4    pragya    90
4        5     umang   NaN
5        6       NaN   100

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"roll_no": [1,2,3,4,5], "name":['sonali','kanishka','sadaf', 'pragya', 'umang']})
v2 = pd.DataFrame({"roll_no": [1,2,3,4,6], "marks":['60','70','80','90','100']})
pd.merge(v1,v2,how = 'left')

   roll_no      name marks
0        1    sonali    60
1        2  kanishka    70
2        3     sadaf    80
3        4    pragya    90
4        5     umang   NaN

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"roll_no": [1,2,3,4,5], "name":['sonali','kanishka','sadaf', 'pragya', 'umang']})
v2 = pd.DataFrame({"roll_no": [1,2,3,4,6], "marks":['60','70','80','90','100']})
pd.merge(v1,v2,how = 'right')

   roll_no      name marks
0        1    sonali    60
1        2  kanishka    70
2        3     sadaf    80
3        4    pragya    90
4        6       NaN   100

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"roll_no": [1,2,3,4,5], "name":['sonali','kanishka','sadaf', 'pragya', 'umang']})
v2 = pd.DataFrame({"roll_no": [1,2,3,4,6], "marks":['60','70','80','90','100']})
pd.merge(v1,v2,how = 'outer', indicator= True)

   roll_no      name marks      _merge
0        1    sonali    60        both
1        2  kanishka    70        both
2        3     sadaf    80        both
3        4    pragya    90        both
4        5     umang   NaN   left_only
5        6       NaN   100  right_only

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"roll_no": [1,2,3,4,5], "name":['sonali','kanishka','sadaf', 'pragya', 'umang']})
v2 = pd.DataFrame({"roll_no": [1,2,3,4,6], "marks":['60','70','80','90','100']})
pd.merge(v1,v2,right_index = True, left_index = True)

   roll_no_x      name  roll_no_y marks
0          1    sonali          1    60
1          2  kanishka          2    70
2          3     sadaf          3    80
3          4    pragya          4    90
4          5     umang          6   100

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"roll_no": [1,2,3,4,5], "name":['sonali','kanishka','sadaf', 'pragya', 'umang']})
v2 = pd.DataFrame({"roll_no": [1,2,3,4,5], "marks":['60','70','80','90','100']})
pd.merge(v1,v2,right_index = True, left_index = True, suffixes = ("9th", "10th"))

   roll_no9th      name  roll_no10th marks
0           1    sonali            1    60
1           2  kanishka            2    70
2           3     sadaf            3    80
3           4    pragya            4    90
4           5     umang            5   100

In [ ]:
import pandas as pd
v1 = pd.DataFrame({"roll_no": [1,2,3,4,5], "name":['sonali','kanishka','sadaf', 'pragya', 'umang']})
v2 = pd.DataFrame({"roll_no": [1,2,3,4,5], "marks":['60','70','80','90','100']})
v3 = pd.DataFrame({"roll_no": [1,2,3,4,5], "marks":['60','70','80','90','100']})
v4 = pd.DataFrame({"roll_no": [1,2,3,4,5], "marks ":['60','70','80','90','100']})
result = pd.merge(v1,v2,on= "roll_no")
result = pd.merge(result,v3,on= "roll_no")
result = pd.merge(result,v4,on= "roll_no")
print(result)

   roll_no      name marks_x marks_y marks
0        1    sonali      60      60     60
1        2  kanishka      70      70     70
2        3     sadaf      80      80     80
3        4    pragya      90      90     90
4        5     umang     100     100    100

## JOIN(): Index based

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A": [1,2,3,4,5], "B":['sonali','kanishka','sadaf', 'pragya', 'umang']})
df2 = pd.DataFrame({"A":['60','70','80','90','100']})
df1.join(df2)                                                       #it will give error as column names are same

ValueError: columns overlap but no suffix specified: Index(['A'], dtype='object')

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A": [1,2,3,4,5], "B":['sonali','kanishka','sadaf', 'pragya', 'umang']})
df2 = pd.DataFrame({"D":['60','70','80','90','100']})
df1.join(df2)

   A         B    D
0  1    sonali   60
1  2  kanishka   70
2  3     sadaf   80
3  4    pragya   90
4  5     umang  100

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A": [1,2,3,4,5], "B":['sonali','kanishka','sadaf', 'pragya', 'umang']}, index = ['A','B','C','D','E'])
df2 = pd.DataFrame({"C": [1,2,3,4,5], "D": ['60', '70', '80', '90','100']})
df1.join(df2)

   A         B   C    D
A  1    sonali NaN  NaN
B  2  kanishka NaN  NaN
C  3     sadaf NaN  NaN
D  4    pragya NaN  NaN
E  5     umang NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"A": [1,2,3,4,5], "B":['sonali','kanishka','sadaf', 'pragya', 'umang']}, index = ['1','2','3','4','5'])
df2 = pd.DataFrame({"C": [1,2,3,4,5], "D": ['60', '70', '80', '90','100']})
df1.join(df2)

   A         B   C    D
1  1    sonali NaN  NaN
2  2  kanishka NaN  NaN
3  3     sadaf NaN  NaN
4  4    pragya NaN  NaN
5  5     umang NaN  NaN

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [2,3,4,5,6], 'B':['A','B','C','D','E']},index = ['A','B','C','D','E'])
df2 = pd.DataFrame({'D': [2,3,], 'C': ['A','C']},index= ['A','B'])
df1.join(df2)
df2.join(df1)

   D  C  A  B
A  2  A  2  A
B  3  C  3  B

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [2,3,4,5,6], 'B':['A','B','C','D','E']},index = ['A','B','C','D','E'])
df2 = pd.DataFrame({'D': [2,3,], 'C': ['A','C']},index= ['A','B'])
df1.join(df2,how = "left")
df2.join(df1,how = "left")

   D  C  A  B
A  2  A  2  A
B  3  C  3  B

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [2,3,4,5,6], 'B':['A','B','C','D','E']},index = ['A','B','C','D','E'])
df2 = pd.DataFrame({'D': [2,3,], 'C': ['A','C']},index= ['A','B'])
df1.join(df2,how = "inner")
df2.join(df1,how = "inner")

   D  C  A  B
A  2  A  2  A
B  3  C  3  B

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [2,3,4,5,6], 'B':['A','B','C','D','E']},index = ['A','B','C','D','E'])
df2 = pd.DataFrame({'D': [2,3,], 'C': ['A','C']},index= ['A','B'])
df1.join(df2,how = "outer")
df2.join(df1,how = "outer")

     D    C  A  B
A  2.0    A  2  A
B  3.0    C  3  B
C  NaN  NaN  4  C
D  NaN  NaN  5  D
E  NaN  NaN  6  E

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [2,3,4,5,6], 'B':['A','B','C','D','E']},index = ['A','B','C','D','E'])
df2 = pd.DataFrame({'C': [2,3,], 'D': ['A','C']},index= ['A','B'])
df1.join(df2,how = "right")
df2.join(df1,how = "right")

     C    D  A  B
A  2.0    A  2  A
B  3.0    C  3  B
C  NaN  NaN  4  C
D  NaN  NaN  5  D
E  NaN  NaN  6  E

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [2,3,4,5,6], 'B':['A','B','C','D','E']},index = ['A','B','C','D','E'])
df2 = pd.DataFrame({'A': [2,3,], 'D': ['A','C']},index= ['A','B'])
df1.join(df2,how = "right",lsuffix="_left")                                #using lsuffix to remove overlapping columns from left DF
df2.join(df1,how = "right",lsuffix="_left")

   A_left    D  A  B
A     2.0    A  2  A
B     3.0    C  3  B
C     NaN  NaN  4  C
D     NaN  NaN  5  D
E     NaN  NaN  6  E

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [2,3,4,5,6], 'B':['A','B','C','D','E']},index = ['A','B','C','D','E'])
df2 = pd.DataFrame({'A': [2,3,], 'D': ['A','C']},index= ['A','B'])
df1.join(df2,how = "right",rsuffix="_right")                               #using rsuffix to rename overlapping columns from right DF
df2.join(df1,how = "right",rsuffix="_right")

     A    D  A_right  B
A  2.0    A        2  A
B  3.0    C        3  B
C  NaN  NaN        4  C
D  NaN  NaN        5  D
E  NaN  NaN        6  E

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [2,3,4,5],'B':['A','B','F','D']})
df2 = pd.DataFrame({'C': [2,3,4,5],'D':['A','B','F','D']})
df3 = pd.DataFrame({'E': [2,3,4,5],'F':['A','B','F','D']})
df1.join([df2,df3])

   A  B  C  D  E  F
0  2  A  2  A  2  A
1  3  B  3  B  3  B
2  4  F  4  F  4  F
3  5  D  5  D  5  D

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [2,3,4,5],'B':['A','B','F','D']})
df2 = pd.DataFrame({'C': [2,3,4,5],'D':['A','B','F','D']})
df3 = pd.DataFrame({'E': [2,3,4,5],'F':['A','B','F','D']})
df1.join(df2).join(df3)

   A  B  C  D  E  F
0  2  A  2  A  2  A
1  3  B  3  B  3  B
2  4  F  4  F  4  F
3  5  D  5  D  5  D

## CONCAT(): Adds data rather than focusing on column name

In [ ]:
import pandas as pd
roll_no= pd.Series([1,2,3,4])
roll_no2= pd.Series([10,20,30,40])
pd.concat([roll_no,roll_no2])

0     1
1     2
2     3
3     4
0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd
roll_no= pd.Series([1,2,3,4])
roll_no2= pd.Series([10,20,30,40])
pd.concat([roll_no,roll_no2], axis = 0)

0     1
1     2
2     3
3     4
0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd
roll_no= pd.Series([1,2,3,4])
roll_no2= pd.Series([10,20,30,40])
pd.concat([roll_no,roll_no2], axis = 1)

   0   1
0  1  10
1  2  20
2  3  30
3  4  40

In [ ]:
import pandas as pd
roll_no= pd.Series([1,2,3,4])
roll_no2= pd.Series([10,20,30,40])
pd.concat([roll_no,roll_no2], axis = 0, ignore_index= True)

0     1
1     2
2     3
3     4
4    10
5    20
6    30
7    40
dtype: int64

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
df2 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
pd.concat([df1,df2])

   A  B
0  1  A
1  2  B
2  3  C
3  4  D
0  1  A
1  2  B
2  3  C
3  4  D

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
df2 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
pd.concat([df1,df2], axis = 1)

   A  B  A  B
0  1  A  1  A
1  2  B  2  B
2  3  C  3  C
3  4  D  4  D

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
df2 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
pd.concat([df1,df2], join = "inner")

   A  B
0  1  A
1  2  B
2  3  C
3  4  D
0  1  A
1  2  B
2  3  C
3  4  D

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
df2 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
pd.concat([df1,df2], join = "outer")

   A  B
0  1  A
1  2  B
2  3  C
3  4  D
0  1  A
1  2  B
2  3  C
3  4  D

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
df2 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
pd.concat([df1,df2], join = "left")                                    #left join is not supported with pd.concat()

ValueError: Only can inner (intersect) or outer (union) join the other axis

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
df2 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
pd.concat([df1,df2], join = "right")                                    #right join is not supported with pd.concat()

ValueError: Only can inner (intersect) or outer (union) join the other axis

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
df2 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
pd.concat([df1,df2], axis = 0, keys= (["A","B"]))

     A  B
A 0  1  A
  1  2  B
  2  3  C
  3  4  D
B 0  1  A
  1  2  B
  2  3  C
  3  4  D

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [1,2,3,4]})
df2 = pd.DataFrame({'A': [1,2,3,4],'B':['A','B','C','D']})
pd.concat([df1,df2], axis = 1)

   A  A  B
0  1  1  A
1  2  2  B
2  3  3  C
3  4  4  D

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [1,2,3,4], 'B':['A','B','C','D']})
df2 = pd.DataFrame({'C': [20,40],'D':['A','B']})
pd.concat([df1,df2], axis = 1)

   A  B     C    D
0  1  A  20.0    A
1  2  B  40.0    B
2  3  C   NaN  NaN
3  4  D   NaN  NaN

Perform validate operations on datasets(checking whether data is correct, valid and follows required rules)

1. One-to-one

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'ID': [1,2,3,4],'name':['sonali','kanishka','sadaf','pragya']})
df2 = pd.DataFrame({'ID': [1,2,3,4],'marks':['10','20','30','40']})
result= pd.merge(df1, df2, on = 'ID', validate= 'one_to_one')
print(result)

   ID      name marks
0   1    sonali    10
1   2  kanishka    20
2   3     sadaf    30
3   4    pragya    40

2. One-to-many

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'ID': [1,2,3,4],'name':['sonali','kanishka', 'sadaf','pragya']})
df2 = pd.DataFrame({'ID': [1,1,3,4],'subject':['english','hindi','science','SST']})
result= pd.merge(df1, df2, on = 'ID', validate= 'one_to_many')
print(result)

   ID    name  subject
0   1  sonali  english
1   1  sonali    hindi
2   3   sadaf  science
3   4  pragya      SST

3. Many-to-one

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'subject': ['english', 'maths', 'science', 'SST'],'marks':[10,30,50,70]})
df2 = pd.DataFrame({'subject': ['english', 'maths', 'science'],'teacher':['A','B','C']})
result= pd.merge(df1, df2, on = 'subject', validate= 'many_to_one')
print(result)

   subject  marks teacher
0  english     10       A
1    maths     30       B
2  science     50       C

4. Many-to-many

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'subject': ['maths', 'maths', 'science', 'SST'],'marks':[10,30,30,70]})
df2 = pd.DataFrame({'subject': ['english', 'maths', 'science'],'teacher':['A','C','C']})
result= pd.merge(df1, df2, on = 'subject', validate= 'many_to_many')
print(result)

   subject  marks teacher
0    maths     10       C
1    maths     30       C
2  science     30       C